name: Public Npm

on:
  push:
    branches: [ publish ]


jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Install modules
        run: pnpm install --no-frozen-lockfile
      - name: Build 
        run: cd packages/smarty-ui-vite && pnpm build
      - name: 'Publish to the npm registry'
        run: pnpm prepublishOnly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
