name: Public Npm

on:
  push:
    branches: [ publish ]


jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    environment: npm
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: cd packages/smarty-ui-vite && pnpm install --no-frozen-lockfile
      - name: Build 
        run: cd packages/smarty-ui-vite && pnpm build 
      - name: 'Publish to the npm registry'
        run: pnpm prepublishOnly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # 跟前面步骤中的 NPM_AUTH_TOKEN 保持一致
