name: Public Npm

on:
  push:
    branches: [ publish ]


jobs:
  publish:
    runs-on: ubuntu-latest
    name: 'publish npm'
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install modules
        run: pnpm install --no-frozen-lockfile
      - name: Build 
        run: cd packages/smarty-ui-vite && pnpm build
      - name: npm auth
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}
      - name: 'Publish to the npm registry'
        run: pnpm publish:every
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
